CREATE TABLE IF NOT EXISTS `orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单号',
  `product_id` BIGINT NOT NULL COMMENT '商品ID',
  `product_title` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '商品标题',
  `product_cover_image` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '商品封面图',
  `product_price` DECIMAL(10,2) NOT NULL COMMENT '商品价格',
  `buyer_id` BIGINT NOT NULL COMMENT '买家ID',
  `buyer_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '买家用户名',
  `buyer_phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '买家手机号',
  `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
  `seller_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '卖家用户名',
  `seller_phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '卖家手机号',
  `status` VARCHAR(20) NOT NULL DEFAULT '待确认' COMMENT '订单状态',
  `note` VARCHAR(200) NULL COMMENT '备注',
  `trade_image` VARCHAR(255) NULL COMMENT '交易现场图',
  `trade_confirmed_at` DATETIME NULL COMMENT '成交确认时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_order_buyer` (`buyer_id`),
  KEY `idx_order_seller` (`seller_id`),
  KEY `idx_order_product` (`product_id`),
  KEY `idx_order_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
