server:
  port: 9103

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.209.128:3306/trade_order_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.209.128
    port: 5672
    username: root
    password: 123456

seata:
  application-id: campus-order-service
  tx-service-group: campus_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.209.128:8848
      namespace: ""
      group: SEATA_GROUP
      cluster: default
      username: nacos
      password: nacos
  service:
    vgroup-mapping:
      campus_tx_group: default
    grouplist:
      default: 192.168.209.128:8091
