server:
  port: 9103

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:192.168.209.128}:${DB_PORT:3306}/${DB_NAME:trade_order_db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.209.128}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PASS:123456}

seata:
  application-id: campus-order-service
  tx-service-group: campus_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${NACOS_ADDR:192.168.209.128:8848}
      namespace: ""
      group: SEATA_GROUP
      cluster: default
      username: ${SEATA_NACOS_USERNAME:nacos}
      password: ${SEATA_NACOS_PASSWORD:nacos}
  service:
    vgroup-mapping:
      campus_tx_group: default
    grouplist:
      default: ${SEATA_ADDR:192.168.209.128:8091}
